## SHLewis
## Programming Assignment 2, due at the end of Week 3
## Coursera course - Johns Hopkins - R Programming, May 2014

################################################################################
## Functions 'makeCacheMatrix' and 'cacheSolve' are defined here.
## Together, these functions are used to:
##    1. Cashe an input matrix.
##          - Do this using the statement: 'mfun <- makeCasheMatrix(m)'
##          - 'm' is the input matrix.
##          - 'mfuns' becomes a list of functions associated with matrix 'm'.
##          -  *** the input matrix is assumed to be invertible ***
##    2. Calculate, cache and return the inverse of the input matrix.
##          - Do this using the statement: 'cacheSolve(mfuns)'. 
##          - The statement in step 1 must be done before casheSolve will work.
##    3. Retrieve the inverse matrix.
##          - Do this using the statement: 'cacheSolve(mfuns)'.
##          - Message 'getting cached data' is printed, indicating the inverse
##            matrix is being retrieved, not calculated.
##    4. Retrieve the input matrix.
##          - Do this using the statement 'mfuns$get()'
################################################################################

## 'makeCacheMatrix' function
## INPUT: x - an invertible matrix
## OUTPUT:  
##    Returns a list of 4 functions:
##          1. 'set' - set the value of the original input matrix
##          2. 'get' - get the value of the original input matrix
##          3. 'setimatrix' - set the value of the inverse matrix
##          4. 'getimatrix' - get the value of the inverse matrix
##    Caches the input matrix in variable x, which remains accessible
##    to the functions in the output list of functions.
makeCacheMatrix <- function(x = matrix()) {
      inv <- NULL                   # initialize inverse matrix (inv)
      set <- function(y) {
            x <<- y
            inv <<- NULL
      }
      get <- function() x
      setimatrix <- function(solve) inv <<- solve
      getimatrix <- function() inv
      list(set = set, get = get,      # return list of functions that is now  
           setimatrix = setimatrix,   # associated with the input matrix
           getimatrix = getimatrix)
}

## 'cacheSolve' function
## INPUT: x - list of functions previously generated by 'makeCacheMatrix'
## OUTPUT: 
##    The inverse of the matrix that was input to 'makeCacheMatrix'  
##    when 'makeCacheMatrix' generated the list of functions (arguement x).
##
## The first time this function is run for the given x arguement, the inverse
## matrix is calculated and cached. With subsequent runs of this function 
## for the given x, the inverse is retrieved from cache (in variable inv,
## which remains accessible to this function and the list of functions, x).
cacheSolve <- function(x, ...) {
      inv <- x$getimatrix()     # Retrieve the inverse matrix
      if(!is.null(inv)) {       # If the retrieved inverse matrix is not null...
            message("getting cached data")
            return(inv)         # return the inverse matrix (and exit)
      }
      data <- x$get()           # Get the original matrix
      inv <- solve(data, ...)   # inv is set to be the inverse matrix
      x$setimatrix(inv)         # cache the inverse matrix
      inv                       # return the inverse matrix
}
